FROM python:3.12-slim

RUN apt-get update
RUN apt-get install -y git

WORKDIR /app

RUN git clone https://github.com/hmelind/flaskr-devops.git
WORKDIR /app/flaskr-devops
RUN git checkout prometheus_metrics

RUN pip install --upgrade pip
RUN pip install --no-cache-dir pytest
RUN pip install --no-cache-dir -e .

RUN mkdir /app/flaskr-devops/instance

EXPOSE 5000

# CMD ["/bin/bash"]

RUN flask --app flaskr init-db

CMD ["flask", "--app", "flaskr", "run", "--host=0.0.0.0"]
